#
#$$$$$$$$\                   $$\      $$$$$$\                                          $$\
#$$  _____|                  $$ |    $$  __$$\                                         $$ |
#$$ |   $$$$$$\   $$$$$$$\ $$$$$$\   $$ /  \__| $$$$$$\  $$$$$$$\   $$$$$$$\  $$$$$$\  $$ | $$$$$$\
#$$$$$\ \____$$\ $$  _____|\_$$  _|  $$ |      $$  __$$\ $$  __$$\ $$  _____|$$  __$$\ $$ |$$  __$$\
#$$  __|$$$$$$$ |\$$$$$$\    $$ |    $$ |      $$ /  $$ |$$ |  $$ |\$$$$$$\  $$ /  $$ |$$ |$$$$$$$$ |
#$$ |  $$  __$$ | \____$$\   $$ |$$\ $$ |  $$\ $$ |  $$ |$$ |  $$ | \____$$\ $$ |  $$ |$$ |$$   ____|
#$$ |  \$$$$$$$ |$$$$$$$  |  \$$$$  |\$$$$$$  |\$$$$$$  |$$ |  $$ |$$$$$$$  |\$$$$$$  |$$ |\$$$$$$$\
#\__|   \_______|\_______/    \____/  \______/  \______/ \__|  \__|\_______/  \______/ \__| \_______|
#####################################################################################################
#This plugin is made by SkyfightTV for everyone
#It works between spigot version 1.7 and 1.18
#This plugin can't be reloaded

#List all the texts you don't want to see in your console.
#Messages that are a WARN or ERROR will remain in the console even if they contain a text that you want to remove!
toHide:
  #- "[ViaVersion]"
  #- "Timings Reset"
#List all the texts you don't want to see in your console.
#Messages that are a WARN or ERROR will still be removed! Be careful, you may miss ERROR if you put too much text.
ToForceHide:
  #- "UUID of added entity already exists"